version: "3.8"

services:
  db:
    image: postgres:latest
    volumes:
      - db-data:/var/lib/postgresql/data
      - ./database/init.sql:/docker-entrypoint-initdb.d/init.sql # sql script to config database
    environment:
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
      POSTGRES_DB: mydatabase
    ports:
      - "5431:5432" # Map ports to the host

volumes:
  db-data:
